### PR TITLE
JENKINS-43446 - java.lang.NoSuchFieldError: DEFAULT_USER_SETTINGS_FILE

### PR DESCRIPTION
**Pull request by tomerc**
Introduce an interceptor for Maven 3.5.0 and above which uses the DEFAULT_USER_SETTINGS_FILE from its new location at "org.apache.maven.cli.configuration.SettingsXmlConfigurationProcessor"

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
Would be nice to have a description for such long pull request

**Comment by tomerc** [comment]
Updated comment

**Comment by aheritier** [comment]
close/reopen to re-trigger the build which was killed by the timeout (> 300%  than the previous build which took 47s)

**Comment by aheritier** [comment]
But one day ... we'll have to refactor the code to avoid all the copy/paste :(

**Comment by olamy** [comment]
lgtm.
Well I agree some refactor is needed to avoid all the copy/paste.

**Comment by tomerc** [comment]
Please hold off 1 day before merging, I found a bug that needs to be addressed before it's merged

**Comment by tomerc** [comment]
I added the following:
1. If in batch mode, disable the ANSI coloring (shows up as gibberish on the Jenkins console)
2. If the maven.conf system.property does not exist, revert to maven 3.3 logic:
`new File(System.getProperty("maven.home", System.getProperty("user.dir", "")), "conf").getCanonicalPath()`

**Comment by aheritier** [comment]
@tomerc take your time, I'll do more intensive tests before merging
About colors output I was thinking to propose to add the [AnsiColor plugin](https://wiki.jenkins-ci.org/display/JENKINS/AnsiColor+Plugin) as a dep of the maven-plugin and automatically configure it if Maven >= 3.5
It shouldn't be so hard. WDYT ?

**Comment by tomerc** [comment]
@aheritier Thanks! I think if we can make use of the AnsiColor plugin that would be great. Right now the -B option is always passed to the embedder and if I remember what Hevre wrote in the mailing list, if you execute Maven via the CLI with -B it would turn off the colors, so this would make it consistent, but perhaps we can override that for Maven 3.5?

**Comment by aheritier** [comment]
Yes confirm, -B deactivates the color like said @hboutemy But yes we can probably hack it :-)

**Comment by dreis2211** [comment]
Hi @aheritier . Any news on the progress?

**Pull request merged**
